### ISSUE TITLE
Any initialization needed?

### ISSUE THREAD

**Issue by rodrigojuarez** [giuseppenovielli/Xam.iOS.IQKeyboardManager#1]
I installed the package in the iOS version for a Xamarin.Forms app, and it doesn't look like anything is happening.
Do I need to perform some initialization?

**Comment by giuseppenovielli** [comment]
Hi @rodrigojuarez yes into your AppDelegate.cs file into FinishLoading method you must configure this library.

For an example check my SampleApp

https://github.com/giuseppenovielli/Xam.iOS.IQKeyboardManager/blob/master/XamIQKeyboardManager.Sample.iOS/AppDelegate.cs

**Comment by giuseppenovielli** [comment]
This is a binding so you can also use all settings available from native library (obj-c)

https://github.com/hackiftekhar/IQKeyboardManager

**Comment by rodrigojuarez** [comment]
Is it the same if I use

IQKeyboardManager.SharedManager().Init();

instead of

IQKeyboardManager.SharedManager().Enable = true;
IQKeyboardManager.SharedManager().ShouldResignOnTouchOutside = true;
IQKeyboardManager.SharedManager().ToolbarManageBehaviour = IQAutoToolbarManageBehaviour.Position;
IQKeyboardManager.SharedManager().EnableAutoToolbar = true;
IQKeyboardManager.SharedManager().ShouldShowToolbarPlaceholder = true;

Thanks!

**Comment by giuseppenovielli** [comment]
> Is it the same if I use
> 
> IQKeyboardManager.SharedManager().Init();
> 
> instead of
> 
> IQKeyboardManager.SharedManager().Enable = true;
> IQKeyboardManager.SharedManager().ShouldResignOnTouchOutside = true;
> IQKeyboardManager.SharedManager().ToolbarManageBehaviour = IQAutoToolbarManageBehaviour.Position;
> IQKeyboardManager.SharedManager().EnableAutoToolbar = true;
> IQKeyboardManager.SharedManager().ShouldShowToolbarPlaceholder = true;
> 
> Thanks!

i thinks yes, should work, but i don't known if all functionality declared are working fine.

So you can simply test into your app anche check it.

**Comment by rodrigojuarez** [comment]
Thanks!
